# Generated by Django 3.2.18 on 2023-05-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(default='checkup', max_length=500)),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_confirm', models.BooleanField(default=False, null=True)),
                ('is_canceled', models.BooleanField(default=False, null=True)),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
