# Generated by Django 3.2.18 on 2023-05-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0004_alter_doctorlocation_pincode'),
        ('appointmentHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visiting_location',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment', to='DoctorApp.doctorlocation'),
            preserve_default=False,
        ),
    ]
