# Generated by Django 3.2.18 on 2023-05-30 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointmentHandler', '0003_auto_20230525_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctor', 'date')},
        ),
    ]
