# Generated by Django 3.2.18 on 2023-05-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_area', models.CharField(blank=True, default='general', max_length=300)),
                ('specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('location_details', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('is_varified_phone', models.BooleanField(default=False)),
                ('available_from_time', models.TimeField()),
                ('available_till_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PatientApp.userprofilepicture')),
            ],
        ),
    ]
