# Generated by Django 3.2.18 on 2023-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0002_doctorlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlocation',
            name='place',
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='pincode',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
