# Generated by Django 3.2.18 on 2023-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_auto_20230511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlocation',
            name='pincode',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
