# Generated by Django 3.2.18 on 2023-06-02 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DoctorApp', '0004_alter_doctorlocation_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEductaionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_course', models.CharField(blank=True, max_length=50, null=True)),
                ('ug_institute', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_course', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_institute', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(default=0, max_length=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
